leftnav:
- identifier: f46b10d9-8c1a-41a4-9430-bacc97ee00b5
  name: page
  pageRef: /pages/page
  weight: 10
- identifier: 9add95cb-21ec-4f9c-80a4-586e5d8147a6
  name: file 14
  pageRef: /resources/file-14_mp4
  weight: 20
- identifier: 574801e8-227d-476f-a88f-6643132b3402
  name: video-test
  pageRef: /resources/video-test
  weight: 30
- identifier: 45d9c05f-11f1-49f1-8ed9-7113736d3312
  name: video-test-2
  pageRef: /resources/video-test-2
  weight: 40
- identifier: fd9747c7-c3ae-42f9-9e78-52c41196d3a9
  name: gal
  pageRef: /video_galleries/gal
  weight: 50
- identifier: c1f60a99-18f7-4d05-963e-c025311c5972
  name: list
  pageRef: /lists/test
  weight: 60
- identifier: 9c770677-eec8-4f2f-8060-512c254d2163
  name: quiz
  pageRef: /pages/quiz
  weight: 70
